controller_manager:
  ros__parameters:
    update_rate: 1000  # Hz

    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    velocity_controller:
        type: velocity_controllers/JointGroupVelocityController



velocity_controller:
  ros__parameters:
    joints:
      - right_wheel_joint
      - left_wheel_joint
    interface_name: velocity
    command_interfaces:
      - velocity
    state_interfaces:
      - position
      - velocity
